# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eecb0748c56f1871675020238cfdfbadd029385b021fcd766c1568f1b69683dbc19999a670204823d2282c01ed13d5c95d1397402354ccb4d1fac6701d5475c

test:
  secret_key_base: c4dc64f27b7d0f42ebed96075605f00d01c8216521912c54aae20ae96160d5120e3254576877bb9b9715d6781a4b0e9d7489d80f5cf82c5385b1e50692b90ad9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
